module.exports = {
  CurrencyModule: require("./submodules/CurrencyModule"),
  DeliriumOrbModule: require("./submodules/DeliriumOrbModule"),
  DivsModule: require("./submodules/DivsModule"),
  EssenceModule: require("./submodules/EssenceModule"),
  FossilModule: require("./submodules/FossilModule"),
  FragmentModule: require("./submodules/FragmentModule"),
  GemModule: require("./submodules/GemModule"),
  InscribedModule: require("./submodules/InscribedModule"),
  InvitationModule: require("./submodules/InvitationModule"),
  JewelModule: require("./submodules/JewelModule"),
  MapModule: require("./submodules/MapModule"),
  OilModule: require("./submodules/OilModule"),
  ScarabModule: require("./submodules/ScarabModule"),
  SextantModule: require("./submodules/SextantModule"),
  UniqueMapsModule: require("./submodules/UniqueMapsModule"),
  AccessoryModule: require("./submodules/AccessoryModule"),
  ArmourModule: require("./submodules/ArmourModule"),
  BaseModule: require("./submodules/BaseModule"),
  BeastModule: require("./submodules/BeastModule"),
  WeaponModule: require("./submodules/WeaponModule"),
  FlaskModule: require("./submodules/FlaskModule"),
};
