name: Publish to JSR

on:
  workflow_run:
    workflows: ["Publish to NPM"]
    types:
      - completed

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Publish package
        run: npx jsr publish